version: '3.3'
services:
  wordpress:
    image: wordpress:6.4.3-php8.1-apache
    ports: 
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: "caminho do BD"
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: ******
      WORDPRESS_DB_NAME: "nome do BD"
      WORDPRESS_TABLE_CONFIG: wp_

    volumes:
      - /home/ec2-user/efs/website:/var/www/html
